### PR TITLE
Make the abstract shorter

### PR DESCRIPTION
**Pull request by Villetaneuse**

### CODE REVIEW

**Comment by thomas-lamiaux** [comment]
@Villetaneuse It is a draft, is it ready ? Have you taken into accounts edits from Théo ?

**Comment by Villetaneuse** [comment]
@Zimmi48 pushed his changes after mine. I can rebase on his work now.

**Comment by Villetaneuse** [comment]
@thomas-lamiaux @Zimmi48 This is ready (if you agree with these changes of course).

**Comment by Zimmi48** [comment]
Sorry, I didn't notice you had opened a PR.

**Pull request merged**
