### PR TITLE
Infrastructure for building tutorials as jsCoq interactive documents.

### PR DESCRIPTION
**Pull request by Zimmi48**
This is based on the code from https://github.com/jscoq/coqdoc-template, with the addition of the "download session" button that was created for @Villetaneuse's class.

In the end, I found out how to make Equations available, it was a matter of modifying `package.json`.

Documentation on how to use and CI/CD configuration for automatic deployment are still to do.

~~I had to comment out part of the Equations tutorial's exercises because otherwise this makes the compilation fail with "There are obligations remaining".~~

### CODE REVIEW

**Comment by Zimmi48** [comment]
Here is a rough demo of the deployed tutorials: http://www.theozimmermann.net/platform-docs/
(The deployment will appear under my own website until we migrate to the Coq organization. Wherever we put this link, we should document that it is temporary.)

**Comment by Villetaneuse** [comment]
Here is my current setup for my courses (I now have 2 which are jsCoq'ed). At the root of the repository we have:
- 1 directory per course with source `.v` files, say `course1` and `course2`
- a `web` directory
- a `scripts` directory with shell scripts to generate subjects and solutions from the `.v` file
- `Makefile`
- `Makefile.in`
- Each course has its own `Makefile`
Here is the main `Makefile`:
```Makefile
.PHONY: serve all course1 course2 clean

all: course1 course 2

course1:
	$(MAKE) -C ipf

course2:
	$(MAKE) -C mathc2p

WEBDIR = web/

$(WEBDIR)node_modules: $(WEBDIR)/package.json $(WEBDIR)/package-lock.json
	cd $(WEBDIR) && npm i

serve: $(WEBDIR)/node_modules
	$(WEBDIR)/node_modules/.bin/http-server $(WEBDIR)

clean:
	$(MAKE) -C course1 clean
	$(MAKE) -C course2 clean
```
Now, each `Makefile` in course1 and course2 is of the form:
```Makefile
WEBDIR = ../web/course1/

LISTE_SUJETS = Sujets
LISTE_CORRIGES = Corrigés

include ../Makefile.in
```
and most of the fun happens in `Makefile.in`:
I don't have time to translate it yet, but in case it helps, here it is:
```Makefile
# Construire les fichiers sujets et corrigés dans un répertoire de fichiers
# Coq .v

# À include dans un Makefile *après* avoir défini les variables :
# WEBDIR : chemin vers le répertoire destiné à contenir les sujets et corrigés
# aux formats .v et .html
# LISTE_SUJETS : chemin d'un fichier contenant la liste des fichiers dont on
# veut générer les sujets associés
# LISTE_CORRIGES : idem pour les corrigés
# Elles sont a priori différentes, donc chaque liste est dans un fichier séparé.
# La liste est formée des noms des fichiers originaux avec leur extension .v,
# à raison d'un par ligne, pour pouvoir écrire brutalement par exemple
# printf '%s\n' *.v >Sujets
# Ensuite si un fichier, par exemple Logique.v est présent dans le fichier
# Sujets, alors make génère
# - Logique_sujet.v
# - $(WEBDIR)Logique_sujet.v
# - $(WEBDIR)Logique_sujet.html
# Si Logique.v est présent dans Corrigés, alors make va générer
# - Logique_corr.v
# - $(WEBDIR)Logique_corr.v
# - $(WEBDIR)Logique_corr.html
#
# Si besoin, voir le contenu du répertoire ipf/ pour un exemple.

.PHONY: all clean
 
SUJETS := $(shell cat $(LISTE_SUJETS))
SUJETS := $(SUJETS:.v=_sujet.v)
SUJETS_V := $(addprefix $(WEBDIR), $(SUJETS))
SUJETS_HTML := $(addprefix $(WEBDIR), $(SUJETS:.v=.html))
CORRIGES := $(shell cat $(LISTE_CORRIGES))
CORRIGES := $(CORRIGES:.v=_corr.v)
CORRIGES_V := $(addprefix $(WEBDIR), $(CORRIGES))
CORRIGES_HTML := $(addprefix $(WEBDIR), $(CORRIGES:.v=.html))

all: $(SUJETS) $(CORRIGES) \
     $(SUJETS_V) $(CORRIGES_V) \
     $(SUJETS_HTML) $(CORRIGES_HTML)

%_sujet.v: %.v
	../scripts/preparation_sujets.sh $<

%_corr.v: %.v
	../scripts/preparation_corrige.sh $<

$(WEBDIR)%.v: %.v
	[ -d $(WEBDIR) ] || mkdir $(WEBDIR)
	cp $< $@ 

%_corr.v: %.v
	../scripts/preparation_corrige.sh $<

$(WEBDIR)%.html: %.v %.glob ../web/jscoqdoc
	../web/jscoqdoc $<
	[ -d $(WEBDIR) ] || mkdir $(WEBDIR)
	mv $*.html $(WEBDIR)

%.glob: %.v
	coqc $<

COQDOC_AUTO = coqdoc.css

clean:
	rm -f *.vo *.vok .*.aux *.glob *.vos \
		$(SUJETS) $(SUJETS_HTML) \
		$(CORRIGES) $(CORRIGES_HTML) \
		$(SUJETS_V) $(CORRIGES_V) \
		$(COQDOC_AUTO)
```
I would have preferred to invite you on the repository, but I'm not an official member of the lab hosting it (and cannot make it totally public because of the solutions).

**Comment by thomas-lamiaux** [comment]
> Here is a rough demo of the deployed tutorials: http://www.theozimmermann.net/platform-docs/ (The deployment will appear under my own website until we migrate to the Coq organization. Wherever we put this link, we should document that it is temporary.)

Can't this be deployed on a web page hosted directly on the repo as for most personal websites ?

**Comment by thomas-lamiaux** [comment]
It seems that it hasn't liked the begin / hide of coqdoc 
image

**Comment by Villetaneuse** [comment]
Yes, sorry should have said so, it's currently not possible (to my knowledge) to hide parts which contain code to be interpreted.

**Comment by thomas-lamiaux** [comment]
Ok, I can always modify the tutorial to make it explicit. 
@Villetaneuse Do you also know if there is an issue with Restart ?

**Comment by Villetaneuse** [comment]
I have never tried it, sorry.

**Comment by Zimmi48** [comment]
> > Here is a rough demo of the deployed tutorials: http://www.theozimmermann.net/platform-docs/ (The deployment will appear under my own website until we migrate to the Coq organization. Wherever we put this link, we should document that it is temporary.)
> 
> Can't this be deployed on a web page hosted directly on the repo as for most personal websites ?

In fact, each GitHub user or organization gets the possibility to deploy a `username.github.io` website, and each project under this user or organization is deployed at the previously mentioned URL with a `/projectname`. My website is hosted on GitHub pages (see the repo `zimmi48.github.io`), but it is associated with a custom domain name, thus the unexpected URL for this project. If that bothers you, what we can do before migrating to the official Coq organization would be to create a dedicated GitHub organization to obtain a URL such as `coq-platform.github.io/docs` or `coq-platform-docs.github.io` (everything is possible). We could also migrate the repo to coq-community, then the website could become `coq-community.org/platform-docs`.

**Comment by Zimmi48** [comment]
Let's merge this, and then I can start working on adding CI/CD.

**Pull request merged**
